### ISSUE TITLE
Minor typo in README

### ISSUE THREAD

**Issue by scottveirs** [nmfs-opensci/nmfs-opensci.github.io#3]
In the 2nd paragraph, first sentence the word `employ` is misspelled as `emplow` --

<img width="625" alt="Screenshot 2024-03-01 at 3 41 33 PM" src="https://github.com/nmfs-opensci/nmfs-opensci.github.io/assets/14044595/52f26a07-0061-42cb-9061-2bd97934e210">

**Comment by eeholmes** [comment]
Thanks! fixed!
